{"name": "test_case1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0", "trace": "self = <test_pytest.Test_caseqq object at 0x0407E778>\n\n    def test_case1(self):\n        print('test1')\n>       assert 1==0\nE       assert 1 == 0\n\ntest_pytest.py:8: AssertionError"}, "start": 1599471782396, "stop": 1599471782396, "uuid": "812b038b-8642-43d1-85eb-0452da99e207", "historyId": "977c36a95b1bdf2193d0b9e743df8353", "testCaseId": "cf70b124ab74ba40510a0a0d76ab7b88", "fullName": "test_pytest.Test_caseqq#test_case1", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Test_caseqq"}, {"name": "host", "value": "YC-20180928UJ17"}, {"name": "thread", "value": "14004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}